python demo.py --input images/2.jpg
python demo.py --input images/5.jpg
python demo.py --input images/6.jpg
python demo.py --input images/7.jpg
python demo.py --input images/10.jpg
python demo.py --input images/11.jpg
python demo.py --input images/12.jpg
python demo.py --input images/13.jpg
python demo.py --input images/14.jpg
python demo.py --input images/15.jpg
python demo.py --input images/16.jpg
python demo.py --input images/19.jpg
python demo.py --input images/21.jpg
python demo.py --input images/22.jpg
python demo.py --input images/23.jpg
python demo.py --input images/24.jpg
python demo.py --input images/25.jpg
python demo.py --input images/27.jpg
python demo.py --input images/28.jpg
python demo.py --input images/29.jpg
python demo.py --input images/30.jpg
python demo.py --input images/31.jpg
python demo.py --input images/32.jpg
python demo.py --input images/33.jpg
python demo.py --input images/34.jpg
python demo.py --input images/37.jpg
python demo.py --input images/39.jpg
python demo.py --input images/40.jpg
python demo.py --input images/42.jpg
python demo.py --input images/43.jpg
python demo.py --input images/44.jpg
python demo.py --input images/46.jpg
python demo.py --input images/47.jpg
python demo.py --input images/50.jpg
python demo.py --input images/53.jpg
python demo.py --input images/54.jpg
python demo.py --input images/56.jpg
python demo.py --input images/57.jpg
python demo.py --input images/58.jpg
python demo.py --input images/60.jpg
python demo.py --input images/61.jpg
python demo.py --input images/63.jpg
python demo.py --input images/64.jpg
python demo.py --input images/66.jpg
python demo.py --input images/67.jpg
python demo.py --input images/68.jpg